# Generated by Django 4.2.16 on 2024-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
