# Generated by Django 4.2.16 on 2024-11-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_customuser_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
