# Generated by Django 4.2.16 on 2024-11-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_customuser_mfa_enabled_customuser_mfa_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mfa_enabled',
            new_name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mfa_secret',
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_auth_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
