# Generated by Django 4.2.16 on 2024-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_remove_customuser_two_factor_auth_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_fa_choice',
            field=models.CharField(blank=True, choices=[('totp', 'TOTP'), ('email', 'Email')], max_length=255),
        ),
    ]
