# Generated by Django 4.2.16 on 2024-11-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_customuser_two_fa_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
